Running on desktop21:
Tue Jan  3 19:19:21 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:03:00.0 Off |                  N/A |
| 13%   27C    P0    54W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
              total        used        free      shared  buff/cache   available
Mem:         257560        1817      255480         134         262      254901
Swap:          4095           0        4095
stdin: is not a tty
total train feature size: 431
num_classes: 431
train size: 11211, valid size 4805
Traceback (most recent call last):
  File "/home/roba/ADS-Data-loading/5.py", line 107, in <module>
    ads3.run_experiment(
  File "/home/roba/ADS-Data-loading/ads3.py", line 145, in run_experiment
    raise Exception("CUDA not available to Torch!")
Exception: CUDA not available to Torch!
total train feature size: 431
num_classes: 431
train size: 11211, valid size 4805
Traceback (most recent call last):
  File "/home/roba/ADS-Data-loading/5.py", line 107, in <module>
    ads3.run_experiment(
  File "/home/roba/ADS-Data-loading/ads3_pt_profile.py", line 149, in run_experiment
    raise Exception("CUDA not available to Torch!")
Exception: CUDA not available to Torch!
total train feature size: 431
num_classes: 431
train size: 11211, valid size 4805
Traceback (most recent call last):
  File "/home/roba/ADS-Data-loading/6.py", line 156, in <module>
    ads3.run_experiment(
  File "/home/roba/ADS-Data-loading/ads3.py", line 145, in run_experiment
    raise Exception("CUDA not available to Torch!")
Exception: CUDA not available to Torch!
total train feature size: 431
num_classes: 431
train size: 11211, valid size 4805
Traceback (most recent call last):
  File "/home/roba/ADS-Data-loading/6.py", line 156, in <module>
    ads3.run_experiment(
  File "/home/roba/ADS-Data-loading/ads3_pt_profile.py", line 149, in run_experiment
    raise Exception("CUDA not available to Torch!")
Exception: CUDA not available to Torch!
total train feature size: 431
num_classes: 431
train size: 11211, valid size 4805
Traceback (most recent call last):
  File "/home/roba/ADS-Data-loading/7.py", line 159, in <module>
    ads3.run_experiment(
  File "/home/roba/ADS-Data-loading/ads3.py", line 145, in run_experiment
    raise Exception("CUDA not available to Torch!")
Exception: CUDA not available to Torch!
total train feature size: 431
num_classes: 431
train size: 11211, valid size 4805
Traceback (most recent call last):
  File "/home/roba/ADS-Data-loading/7.py", line 159, in <module>
    ads3.run_experiment(
  File "/home/roba/ADS-Data-loading/ads3_pt_profile.py", line 149, in run_experiment
    raise Exception("CUDA not available to Torch!")
Exception: CUDA not available to Torch!
